QT.quick3deffects_private.VERSION = 6.4.0
QT.quick3deffects_private.name = QtQuick3DEffects
QT.quick3deffects_private.module =
QT.quick3deffects_private.libs = $$QT_MODULE_LIB_BASE
QT.quick3deffects_private.includes = 
QT.quick3deffects_private.frameworks = 
QT.quick3deffects_private.depends = quick3deffects
QT.quick3deffects_private.uses = 
QT.quick3deffects_private.module_config = v2 internal_module
QT.quick3deffects_private.enabled_features = 
QT.quick3deffects_private.disabled_features = 
